INSERT INTO address_province (name, id) VALUES ('Aceh (NAD)', '11');
INSERT INTO address_province (name, id) VALUES ('Bali', '51');
INSERT INTO address_province (name, id) VALUES ('Banten', '36');
INSERT INTO address_province (name, id) VALUES ('Bengkulu', '17');
INSERT INTO address_province (name, id) VALUES ('DI Yogyakarta', '34');
INSERT INTO address_province (name, id) VALUES ('DKI Jakarta', '31');
INSERT INTO address_province (name, id) VALUES ('Gorontalo', '75');
INSERT INTO address_province (name, id) VALUES ('Jambi', '15');
INSERT INTO address_province (name, id) VALUES ('Jawa Barat', '32');
INSERT INTO address_province (name, id) VALUES ('Jawa Tengah', '33');
INSERT INTO address_province (name, id) VALUES ('Jawa Timur', '35');
INSERT INTO address_province (name, id) VALUES ('Kalimantan Barat', '61');
INSERT INTO address_province (name, id) VALUES ('Kalimantan Selatan', '63');
INSERT INTO address_province (name, id) VALUES ('Kalimantan Tengah', '62');
INSERT INTO address_province (name, id) VALUES ('Kalimantan Timur', '64');
INSERT INTO address_province (name, id) VALUES ('Kalimantan Utara', '65');
INSERT INTO address_province (name, id) VALUES ('Kepulauan Bangka Belitung', '19');
INSERT INTO address_province (name, id) VALUES ('Kepulauan Riau', '21');
INSERT INTO address_province (name, id) VALUES ('Lampung', '18');
INSERT INTO address_province (name, id) VALUES ('Maluku', '81');
INSERT INTO address_province (name, id) VALUES ('Maluku Utara', '82');
INSERT INTO address_province (name, id) VALUES ('Nusa Tenggara Barat (NTB)', '52');
INSERT INTO address_province (name, id) VALUES ('Nusa Tenggara Timur (NTT)', '53');
INSERT INTO address_province (name, id) VALUES ('Papua', '91');
INSERT INTO address_province (name, id) VALUES ('Papua Barat', '92');
INSERT INTO address_province (name, id) VALUES ('Papua Pegunungan', '95');
INSERT INTO address_province (name, id) VALUES ('Papua Selatan', '93');
INSERT INTO address_province (name, id) VALUES ('Papua Tengah', '94');
INSERT INTO address_province (name, id) VALUES ('Riau', '14');
INSERT INTO address_province (name, id) VALUES ('Sulawesi Barat', '76');
INSERT INTO address_province (name, id) VALUES ('Sulawesi Selatan', '73');
INSERT INTO address_province (name, id) VALUES ('Sulawesi Tengah', '72');
INSERT INTO address_province (name, id) VALUES ('Sulawesi Tenggara', '74');
INSERT INTO address_province (name, id) VALUES ('Sulawesi Utara', '71');
INSERT INTO address_province (name, id) VALUES ('Sumatera Barat', '13');
INSERT INTO address_province (name, id) VALUES ('Sumatera Selatan', '16');
INSERT INTO address_province (name, id) VALUES ('Sumatera Utara', '12');
